### ISSUE TITLE
Help building lineageos

### ISSUE THREAD

**Issue by skjnldsv** [TingyiChen/device_xiaomi_jasmine_sprout#1]
Hello!
Could you also add the manifest you're using to build the lineageos releases for jasmine_sprout?

Thanks :)

**Comment by skjnldsv** [comment]
I tried using this, but had some issues.
I'm still trying to build the whole rom, but I am failing:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="TingyiChen/device_xiaomi_jasmine_sprout" path="device/xiaomi/jasmine_sprout" remote="github" />
  <project name="TingyiChen/device_xiaomi_wayne" path="device/xiaomi/wayne" remote="github" />
  <project name="TingyiChen/device_xiaomi_wayne-common" path="device/xiaomi/wayne-common" remote="github" />

  <project name="TingyiChen/vendor_xiaomi_jasmine_sprout" path="vendor/xiaomi/jasmine_sprout" remote="github" />
  <project name="TingyiChen/vendor_xiaomi_wayne" path="vendor/xiaomi/wayne" remote="github" />
  <project name="TingyiChen/vendor_xiaomi_wayne-common" path="vendor/xiaomi/wayne-common" remote="github" />
  
  <project name="LineageOS/android_kernel_xiaomi_sdm660" path="kernel/xiaomi/sdm660" remote="github" />

  <project name="LineageOS/android_device_qcom_common" path="device/qcom/common" remote="github" />
</manifest>
```

Shouldn't we use the official jasmine kernel instead?
```  xml
<project name="MiCode/Xiaomi_Kernel_OpenSource" path="kernel/xiaomi/sdm660" remote="github" revision="jasmine-o-oss" />
```

**Comment by TingyiChen** [comment]
https://github.com/guaiyihu/android_kernel_xiaomi_whyred

**Comment by skjnldsv** [comment]
Hey @TingyiChen 
Thanks for your answer! Could you also share your manifest?
For the kernel you just linked, what branch are you using?

Thanks :tada:

**Comment by TingyiChen** [comment]
Default. I don't use manifest

**Comment by skjnldsv** [comment]
Thanks @TingyiChen!

Sorry, I'm kind of new to this.
How do you compile lineageos without a manifest then?

**Comment by TingyiChen** [comment]
Manually clone repos

**Comment by skjnldsv** [comment]
@TingyiChen Okay, make sense I guess.
So looking at my repo list above, am I using the same you use to make your lineageos releases?
Am I missing some?

Thanks you so much for your help! :hugs:

**Comment by skjnldsv** [comment]
I'm almost there, but encountering failures:

``` c
In file included from hardware/qcom/audio-caf/msm8998/hal/acdb.c:29:
In file included from hardware/qcom/audio-caf/msm8998/hal/platform_api.h:22:
In file included from out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/voice_params.h:5:
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:18: error: field has incomplete type 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:442:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;         /* reference timestamp */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:451:18: error: field has incomplete type 'struct timespec'
        struct timespec audio_tstamp;   /* sample counter, wall clock, PHC or on-demand sync'ed */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:452:18: error: field has incomplete type 'struct timespec'
        struct timespec driver_tstamp;  /* useful in case reference system tstamp is reported with delay */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:454:30: error: invalid application of 'sizeof' to an incomplete type 'struct timespec'
        unsigned char reserved[52-2*sizeof(struct timespec)]; /* must be filled with zero */
                                    ^     ~~~~~~~~~~~~~~~~~
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:461:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;         /* Timestamp */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:463:18: error: field has incomplete type 'struct timespec'
        struct timespec audio_tstamp;   /* from sample counter or wall clock */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:632:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;         /* Timestamp */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:744:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;         /* Timestamp - last update */
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:794:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:937:18: error: field has incomplete type 'struct timespec'
        struct timespec tstamp;
                        ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:938:29: error: invalid application of 'sizeof' to an incomplete type 'struct timespec'
        unsigned char reserved[128-sizeof(struct timespec)];
                                   ^     ~~~~~~~~~~~~~~~~~
out/target/product/jasmine_sprout/obj/KERNEL_OBJ/usr/include/sound/asound.h:441:9: note: forward declaration of 'struct timespec'
        struct timespec trigger_tstamp; /* time when stream was started/stopped/paused */
               ^
1 warning and 12 errors generated.
[ 75% 87749/116024] target arm C: audio.primary.sdm660_32 <= hardware/qcom/audio-caf/msm8998/hal/audio_extn/audio_extn.c
[ 75% 87750/116024] target arm C: audio.primary.sdm660_32 <= hardware/qcom/audio-caf/msm8998/hal/msm8916/platform.c
In file included from hardware/qcom/audio-caf/msm8998/hal/msm8916/platform.c:30:
system/core/libcutils/include_vndk/cutils/log.h:38:2: warning: "Deprecated: don't include cutils/log.h, use either android/log.h or log/log.h" [-W#warnings]
#warning "Deprecated: don't include cutils/log.h, use either android/log.h or log/log.h"
 ^
1 warning generated.
[ 75% 87751/116024] Building with Jack: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/TeleService_intermediates/with-local/classes.dex
[ 75% 87752/116024] Building with Jack: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/Telecom_intermediates/with-local/classes.dex
[ 75% 87753/116024] Building with Jack: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/WallpaperCropper_intermediates/with-local/classes.dex
[ 75% 87754/116024] Building with Jack: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/Settings_intermediates/with-local/classes.dex
[ 75% 87755/116024] Building with Jack: /srv/src/LINEAGE_15_1/out/target/common/obj/APPS/SystemUI_intermediates/with-local/classes.dex
ninja: build stopped: subcommand failed.
11:44:29 ninja failed with: exit status 1
```

**Comment by TingyiChen** [comment]
Use mko-mr1

**Comment by skjnldsv** [comment]
@TingyiChen Thanks it worked!
Though I cannot flash it! I was on jasmine before, I guess you cannot flash a jasmine_sprout zip?

**Comment by TingyiChen** [comment]
Download latest TWRP from my afh.

**Comment by skjnldsv** [comment]
@TingyiChen Thanks. Flashing works, but unfortunately your rom is unusable (modem fails, bluetooth too... on the jasmine_sprout one, not the jasmine from December). And mine as well!

```
01-13 11:17:24.470  6656  6686 E AndroidRuntime: FATAL EXCEPTION: DdsCardSelectionController
01-13 11:17:24.470  6656  6686 E AndroidRuntime: Process: com.android.phone, PID: 6656
01-13 11:17:24.470  6656  6686 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.DdsCardSelectionController.savePrefNetworkInDb(Unknown Source:13)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.DdsCardSelectionController.setPreferredGWNetworkType(Unknown Source:45)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.DdsCardSelectionController.handleTimeOut(Unknown Source:113)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.DdsCardSelectionController.-wrap8(Unknown Source:0)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at com.qualcomm.qti.internal.telephony.DdsCardSelectionController$MyHandler.handleMessage(Unknown Source:191)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-13 11:17:24.470  6656  6686 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
01-13 11:17:24.476  2055  2525 W ActivityManager: Process com.android.phone has crashed too many times: killing!
01-13 11:17:24.476  2055  2525 W ActivityManager:   Force finishing activity com.android.phone/.MobileNetworkSettings
01-13 11:17:24.485  2055  2525 I WindowManager: Failed to capture screenshot of Token{5a93915 ActivityRecord{5ce72cc u0 com.android.phone/.MobileNetworkSettings t532 f}} appWin=Window{6f41edf u0 com.android.phone/com.android.phone.MobileNetworkSettings} drawState=4
01-13 11:17:24.504  2055  2525 W ActivityManager:   Force finishing activity com.android.phone/.MobileNetworkSettings
```
```
01-13 11:19:21.351  2055  2777 E ActivityManager: Sending non-protected broadcast org.codeaurora.intent.action.ACTION_NETWORK_SPECIFIER_SET from system 8478:com.android.phone/1001 pkg com.android.phone
01-13 11:19:21.351  2055  2777 E ActivityManager: java.lang.Throwable
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at com.android.server.am.ActivityManagerService.checkBroadcastFromSystem(ActivityManagerService.java:19169)
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntentLocked(ActivityManagerService.java:19774)
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at com.android.server.am.ActivityManagerService.broadcastIntent(ActivityManagerService.java:19916)
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:240)
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2989)
01-13 11:19:21.351  2055  2777 E ActivityManager: 	at android.os.Binder.execTransact(Binder.java:697)
```

**Comment by TingyiChen** [comment]
Will check when got time....

**Comment by skjnldsv** [comment]
Hello again :)
I see you're also a maintainer for the mokee jasmine_sprout repo.
They're using a manifest or a config for their automated builds, right?
I could not find it, maybe you have it? That would maybe help me at least successfully build something?

Thanks :v:
